# Generated by Django 4.2.7 on 2023-11-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_task_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='', upload_to='main_app/static/uploads'),
        ),
    ]
