# Generated by Django 4.2.7 on 2023-11-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='workspace',
        ),
    ]
