# Generated by Django 4.2.7 on 2023-11-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_task_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='workspace',
        ),
        migrations.AddField(
            model_name='workspace',
            name='tasks',
            field=models.ManyToManyField(to='main_app.task'),
        ),
    ]
